<?php

namespace App\Filament\Resources\MONITORAMENTO\CONTATO;

use App\Filament\Resources\MONITORAMENTO\CONTATO\ContatoMonitoramentoResource\Pages;
use App\Filament\Resources\MONITORAMENTO\CONTATO\ContatoMonitoramentoResource\RelationManagers;
use App\Models\MONITORAMENTO\CONTATO\ContatoMonitoramento;
use Faker\Provider\Text;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class ContatoMonitoramentoResource extends Resource
{
    protected static ?string $model = ContatoMonitoramento::class;

    protected static ?string $navigationGroup = 'MONITORAMENTO';

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    protected static ?string $modelLabel = 'Contato do Monitoramento';

    protected static ?string $pluralModelLabel = 'Contatos do Monitoramento';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Select::make('tipo_contato_id')
                    ->relationship('tipo_contato', 'name')
                    ->createOptionForm([
                        Forms\Components\TextInput::make('name')
                            ->required(),
                        Forms\Components\TextInput::make('description')
                            ->maxLength(191),
                    ]),
                Forms\Components\TextInput::make('name')
                    ->maxLength(100),
                Forms\Components\TextInput::make('contato')
                    ->maxLength(100),
                Forms\Components\TextInput::make('descricao')
                    ->maxLength(191),
                Forms\Components\Select::make('estados')
                    ->multiple()
                    ->relationship('estados', 'name')
                    ->createOptionForm([
                        Forms\Components\TextInput::make('name')
                            ->required(),
                        Forms\Components\TextInput::make('sigla')
                            ->maxLength(191),
                        Forms\Components\Select::make('regiao_id')
                            ->relationship('regiao', 'name')
                            ->createOptionForm([
                                Forms\Components\TextInput::make('name')
                                    ->required()
                                    ->unique(),
                                Forms\Components\TextInput::make('description')
                                    ->maxLength(191),
                            ]),
                    ])
                    ->preload()
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label('Nome do Contato')
                    ->searchable(),
                Tables\Columns\TextColumn::make('contato')
                    ->searchable(),
                Tables\Columns\TextColumn::make('tels.numero')
                    ->label('Telefone do Contato')
                    ->searchable(),
                Tables\Columns\TextColumn::make('tipo_contato.name')
                    ->label('Descrição do Contato')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('descricao')
                    ->label('Descrição do Contato')
                    ->searchable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->label('Data de Criação')
                    ->dateTime()
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\ViewAction::make()
                    ->iconButton(),
                Tables\Actions\EditAction::make()
                    ->iconButton(),
                Tables\Actions\DeleteAction::make()
                    ->iconButton(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateActions([
                Tables\Actions\CreateAction::make(),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ManageContatoMonitoramentos::route('/'),
        ];
    }

    public static function getNavigationBadge(): ?string
    {
        return self::getModel()::count(); // TODO: Change the autogenerated stub
    }
}
